name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-20.04,
          # macos-10.15,
          windows-2022
        ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.3.0'
          java-version: '17'

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Execute build
        run: ./gradlew :core:clean :core:build
